on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/flake.yml'
      - 'src/**'
      - 'Cargo.*'
      - "*.toml"
      - "flake.*"
      - "*.nix"
      - "*.rs"
  push:
    branches: [main]
    paths:
      - '.github/workflows/flake.yml'
      - 'src/**'
      - 'Cargo.*'
      - "*.toml"
      - "flake.*"
      - "*.nix"
      - "*.rs"

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  check:
    permissions:
      contents: write
    name: Check Nix Flake
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v10
      - name: Setup Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: extractions/setup-just@v2
      - name: Generate
        run: just idump
      - uses: stefanzweifel/git-auto-commit-action@v5
