on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/flake.yml'
      - 'src/**'
      - 'Cargo.*'
      - "*.toml"
      - "flake.*"
      - "*.nix"
      - "*.rs"
  push:
    branches: [main]
    paths:
      - '.github/workflows/flake.yml'
      - 'src/**'
      - 'Cargo.*'
      - "*.toml"
      - "flake.*"
      - "*.nix"
      - "*.rs"

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  check:
    name: Check Nix Flake
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v10
      - name: Setup Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Nix Flake Check
        id: flake-check
        run: |
          output=$(nix flake check --all-systems 2>&1 || true)
          echo "$output"
          if [[ $output =~ For\ full\ logs,\ run\ \'(nix\ log\ .*)\'\. ]]; then
            echo "log_command=${BASH_REMATCH[1]}"
            echo "log_command=${BASH_REMATCH[1]} | tail -n 500" >> $GITHUB_OUTPUT
          fi
      - name: Get Full Logs
        if: steps.flake-check.outputs.log_command
        run: ${{ steps.flake-check.outputs.log_command }}
